gdb-stub: refactor write_memory in  DebugMemoryInterface
This includes the following changes:

	* Use a separate index for the source (data) and
	  destination (buf) buffer.
	* Infer destination buffer size from data length,
	  not from nbytes.
	* Correctly check strtol(3) return value.
	* Ensure that strtol(3) return value fits into uint8_t.
	* Use a local buffer, instead of std::string::substr.

Without these change memory writes with gdb-mc would fail with the
following error message:

	Error: (E549) uncaught exception: vector::_M_range_check:
	       __n (which is 2) >= this->size() (which is 2)
	In file: ../../../src/sysc/kernel/sc_except.cpp:101

This was due to out-of-bounds error during the assignment:

	buf.at(i) = byte;